---
title: "Class-2019-03-12"
author: "Alistair Gluck"
date: "3/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(lubridate)
```

```{r, cache = TRUE}

spain <- read_csv("https://pollofpolls.eu/get/polls/ES-parliament/format/csv", 
                  col_types = cols(
                                  date = col_date(format = ""),
                                  firm = col_character(),
                                  n = col_double(),
                                  sd = col_double(),
                                  source = col_character(),
                                  PP = col_double(),
                                  PSOE = col_double(),
                                  BNG = col_double(),
                                  CC = col_double(),
                                  ERC = col_double(),
                                  PNVEAJ = col_double(),
                                  Cs = col_double(),
                                  VOX = col_double(),
                                  Podemos = col_double(),
                                  EHBildu = col_double(),
                                  PACMA = col_double(),
                                  PDeCAT = col_double()
                                  ))
  #clean_names() %>% 
  #mutate(month = parse_date(date, format = "%Y%m%d"))
```



```{r}
good_firms <- spain %>% 
  count(firm) %>% 
  filter(n >= 40) %>% 
  pull(firm)

good_firms

```

```{r}
spain %>% 
  filter(date > Sys.Date() - 365) %>% 
  filter(firm %in% good_firms) %>%
  gather(key = party, value = Podemos, PSOE, PP, Cs, VOX))
  # ggplot(aes(x = date, y %in% c(Podemos, PSOE, PP, Cs, VOX))) +
  # geom_line()
```
         
         # %in% c("Celeste-Tel",			
         #              "GAD3",			
         #              "Invymark",			
         #              "Metroscopia",			
         #              "NC Report",		
         #              "Sigma Dos",			
         #              "Simple Lógica")) %>% 


